#' Title
#'
#' @param nb_combi Maximum number of species in a combination
#' @param hv_list A list of hypervolumes
#' @param species_list_hv_selected List of the species represented by the hypervolumes
#'
#' @return
#' @export
#'
#' @examples
hypervolume_overlap <- function(hv_list){


  #######################################################################
  #######################################################################

  # Generated by using Rcpp::compileAttributes() -> do not edit by hand
  # Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

  kdtree_build_intl <- function(d, nr, nc) {
    .Call('_hypervolume_kdtree_build_intl', PACKAGE = 'hypervolume', d, nr, nc)
  }

  kdtree_ball_query_multiple <- function(tr, ptlist, nr, nc, r, verb) {
    .Call('_hypervolume_kdtree_ball_query_multiple', PACKAGE = 'hypervolume', tr, ptlist, nr, nc, r, verb)
  }

  kdtree_ball_query_id_multiple <- function(tr, ptlist, nr, nc, r, verb) {
    .Call('_hypervolume_kdtree_ball_query_id_multiple', PACKAGE = 'hypervolume', tr, ptlist, nr, nc, r, verb)
  }

  kdtree_range_query_multiple <- function(tr, pminlist, pmaxlist, nr, nc, verb) {
    .Call('_hypervolume_kdtree_range_query_multiple', PACKAGE = 'hypervolume', tr, pminlist, pmaxlist, nr, nc, verb)
  }

  fastPdist2 <- function(Ar, Br) {
    .Call('_hypervolume_fastPdist2', PACKAGE = 'hypervolume', Ar, Br)
  }


  evalfspherical <- function(data, radius, points, getid.nearestneighbor=FALSE, verbose=TRUE)

  {
    result = rep(NA, nrow(points))

    points_numeric = t(as.matrix(points))
    nr = nrow(points)
    nc = ncol(points)

    tree <- kdtree_build(data,verbose=verbose)

    result <- kdtree_ball_query_multiple(tree, points_numeric, nr, nc, radius, verbose)


    rm(tree)


    return(result)
  }

  kdtree_build <- function(data, verbose=TRUE)
  {
    if (any(class(data) == "data.frame"))
    {
      data <- as.matrix(data)
    }
    if (any(class(data) == "matrix"))
    {
      if (verbose==TRUE)
      {
        cat("\nBuilding tree... \n")
      }

      kdt <- kdtree_build_intl(t(data),nrow(data),ncol(data))

      if (verbose==TRUE)
      {
        cat("done.\n")
      }

      return(kdt)
    }
    else
    {
      stop("Input data not a matrix or data frame")
    }
  }
  ############################################################################
  ############################################################################

  nb_combi <- dlg_list(title = "Chose the max number of species in combinations", c(2:(length(hv_list@HVList))))$res
  nb_combi <- as.numeric(nb_combi)

  species_list_hv_selected <- c()
  for (i in 1:length(hv_list@HVList)){
    species_list_hv_selected <- c(species_list_hv_selected, hv_list[[i]]@Name)
  }

  list_combi <- do.call("c", lapply(1:nb_combi, function(i) combn(species_list_hv_selected, i, FUN = list)))
  list_combi <- list_combi[-(1:length(species_list_hv_selected))]

  warning(paste0("combinations to calculate :" , as.character(length(list_combi))))


  combi_df <- data.frame(matrix(ncol = nb_combi, nrow = 0))

  for ( i in 1:length(list_combi)){
    vect <- list_combi[[i]]
    length(vect) <- nb_combi+1
    combi_df <- rbind(combi_df, vect)
  }

  combi_df[is.na(combi_df)] <- "None"

  for (i in 1:length(combi_df[,1])){
    ind <- c()
    hv_list_test <- new("HypervolumeList")

    for (j in 1:length(species_list_hv_selected)){
      for (q in 1:length(combi_df[1,])){

        if (combi_df[[q]][i] == hv_list[[j]]@Name){
          ind <- c(ind, j)
        }
      }
    }

    hv_list_test <-  hv_list[[ind]]
    intersection <- HV_intersection(hv_list_test)
    combi_df[[nb_combi+1]][i] <- intersection@Volume
  }

  #rescale
  combi_df[nb_combi+1] <- as.numeric(combi_df[[nb_combi+1]])
  rescaled_combi_df <-cbind(combi_df[1:nb_combi], apply(combi_df[nb_combi+1], MARGIN = 2, FUN = function(X) (X - min(X))/diff(range(X))))


  #species_abiotics_df_sub <- rescaled_abiotics_save %>% filter(
  #species %in% c(species_list_hv_selected)
  #)

  #rescaled_abiotics_df <- rescale.many(species_abiotics_df_sub, c(2:11))
  return(rescaled_combi_df)
}

